version: "3"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: synapsis
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TEMPLATE_DIR: "/app/src/views"
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    image: okkyroydirgantara/golang-fiber-synapsis-api:latest
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
